### ISSUE TITLE
DMARC with system emails

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/cyber.dhs.gov#12]
(disclaimer, I'm brand new to DMARC)

Does DMARC `p=reject`cause issues with server generated from inside the network which isn’t associated with a mailbox? E.g. cron job emails coming from a system where the sender is something like `root@foo.llnl.gov` ?

**Comment by h-m-f-t** [comment]
DMARC shouldn't hinder the _sending_ of mail at all. It could potentially hinder the _receipt_ of mail, but (and I don't know the answer here) it seems likely that mailboxes receiving cron job emails are not likely to be performing DMARC validation on incoming emails generally. And if they do, they are likely to be reliant on the internal DNS, which has a fair likelihood of being different from external DNS for domains shared between the two.

**Comment by AntiFreeze** [comment]
You can also make sure internal systems are listed in your domain's SPF record, and then they'll be received without issue.

**Comment by h-m-f-t** [comment]
Also, consider not using the same domain name internally as you do internet-facing-- but I get that's probably an enterprise architecture battle and not one easily won.

@IanLee1521 Closing for now;, feel free to share more info as needed.
