### ISSUE TITLE
Encourage stronger SSL Protocols

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/cyber.dhs.gov#13]
Are there any thoughts about not just saying “don’t use SSLv2 / SSLv3” but also towards saying “only use TLS1.2" ?

I’m in the middle of looking at fixing up a number of internal servers and trying to figure out what we can get away with. It appears that TLS1.2 is supported in all the modern desktop browsers, but maybe we still need TLS1.1 for some mobile and other platforms? This led me to wonder if we should be more aggressive about pushing on the protocol requirements (and there is possibly a similar argument for ciphers).

**Comment by h-m-f-t** [comment]
While this is a good suggestion, this isn't the role of BOD 18-01. 

There could potentially be future binding operational directives targeting the speedy adoption of more modern TLS versions (and indeed, NIST has [already issued guidance](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r1.pdf#page=7) stating that TLS 1.1 should be the minimum version used for external systems).
