### ISSUE TITLE
non-.gov domains

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/cyber.dhs.gov#14]
In https://github.com/dhs-ncats/cyber.dhs.gov/blob/master/pages/https.md#preloading I saw a link off to https://policy.cio.gov/web-policy/domain/ which led me to ask, how does one define “non-.gov domain” ?  

I image that domains owned / operated by the agency directly are in scope, but what about contractor operated domains?

**Comment by h-m-f-t** [comment]
A "non-.gov domain" is, I think, straightforward: does the domain use the .gov TLD in the public DNS? If so, it's a .gov domain. However, the more relevant question for BOD 18-01 is "is the domain a 'federal domain'?" (for lack of a better term).

https://policy.cio.gov/web-policy/domain, from M-17-06, explains that federal executive branch agencies are to "use only an approved .gov or .mil domain for its official public-facing websites." It also states: 
>The requirement to use only approved government domains does not apply in circumstances where the agency is a user or a customer of a third-party website or service that resides on a non-governmental domain.

So, these policies wouldn't apply to, e.g., `twitter.com/dhsgov` or something like `agency-name.slack.com` (or `beltway-bandit.com`, who might run systems on behalf of a federal agency). 

However, [FISMA 2014](https://www.congress.gov/bill/113th-congress/senate-bill/2521/text) makes clear that a federal system is a federal system regardless of whether it is "used or operated by an agency or by a contractor of an agency or other organization on behalf of an agency". 

IANAL, but it seems like if an agency owns a domain (billing, administrative, technical) or is the proximate cause and support for such a domain, it's in scope. I'm sure there are other, better heuristics.

The Directive doesn't (and the implementation guidance shouldn't) make a recommendation to a list of TLDs in scope; anything an agency owns is in scope.

**Comment by IanLee1521** [comment]
Thanks!
