### ISSUE TITLE
Define what a second-level domain is

### ISSUE THREAD

**Issue by AntiFreeze** [dhs-ncats/cyber.dhs.gov#18]
The text of the BOD and the compliance guide refer to second-level domains, but there is never explicit guidance around what this means.

**Comment by h-m-f-t** [comment]
Hi @AntiFreeze, I agree this can be clarified. 

The intention of the directive is that a second-level domain is analogous to a [public suffix](https://publicsuffix.org/), and indeed, our [trustymail](https://github.com/dhs-ncats/trustymail/) scanner is PSL aware.

"[What is the scope of BOD 18-01?](https://cyber.dhs.gov/guide/#what-is-the-scope-of-bod-18-01)" in the FAQ section says:

> The Directive applies to internet-facing agency information systems, which encompasses those systems directly managed by an agency as well as those operated on an agency’s behalf. Its primary focus is on agency mail and web infrastructure, __regardless of domain suffix__.

This is intended to signal to agencies that the BOD applies to more than .gov, but I agree it should be self-evident what second-level domain is. We'll give it a shot, or we'd welcome a pull request. 🇺🇸
