### ISSUE TITLE
Do DMARC clients actually respect the Public Suffix List?

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/cyber.dhs.gov#24]
The RFC says they should be aware of the PSL, but I wonder if anyone has any insight into whether this actually happens in practice.

**Comment by AntiFreeze** [comment]
Yes, this is exactly what happens in practice.

And of course, there are issues with the public suffix list, which led the IETF to charter DBOUND (https://datatracker.ietf.org/wg/dbound/charter/), which unfortunately was not able to come up with a standardized solution.

**Comment by h-m-f-t** [comment]
Good question, good answer.
