### ISSUE TITLE
Display absolute dates for deadlines somewhere

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/cyber.dhs.gov#5]
The BOD uses relative times (`120 days from...`), and it would be much more helpful to just have specific dates shown somewhere. 

I would definitely recommend updating the Checklist to show those (even if addition to the relative dates).

It would also be great to change text on the homepage, but if you don't want to change the text on the home page to keep it matched to the PDF, then I would link the `120 days from...` text to the Checklist, and then have the Checklist express it in absolute dates.

**Comment by h-m-f-t** [comment]
cc: @BradleyLundy @JoshuaStankus

This is a great idea, thanks @konklone! I'll make sure we're all aligned internally on the dates and make this change to the site.
